Neos:
  Neos:
    fusion:
      autoInclude:
        Naturlife.KlarnaOnSiteMessaging: true
    nodeTypes:
      groups:
        klarna:
          position: 500
          label: 'Klarna'
          collapsed: true
